Added option B for blob support
scopely/mapper pull request #15
Opened 2017-04-03 16:58 UTC by mdiazjusticia

Option attributeValue.getB for loading binary data from DynamoDB

2017-04-03 17:06 UTC, avram requested changes
Can you add this to the tests? Also wondering how you're representing binary content in the JSON.

2017-04-03 17:06 UTC, casidiablo requested changes
I'm not sure it will "_just work_". This covers the deserialization of records... but I'm especially intrigued about the serialization counterpart.

Can you please add a test to exercise this new capability?

2017-04-04 12:29 UTC, avram requested changes
In addition to my comment, can you make sure that you have a test case that uses a model object that you are round tripping to Dynamo?

2017-04-04 12:29 UTC, avram commented on src/main/java/com/scopely/mapper/JsonNodeAttributeValueMapper.java
> +                try {
This doesn't look right. Surely you don't mean to use this logic for the MISSING case.

2017-04-04 16:30 UTC, casidiablo approved these changes

2017-04-04 16:54 UTC, avram reviewed
On phone with bad internet, but two non blocking notes: Include cause when wrapping the exception as MappingException and always specify a charset when calling getBytes on a string. Even in tests- treat the version with default charset as deprecated.

2017-04-05 18:26 UTC, avram approved these changes

2017-04-05 18:26 UTC, avram commented on src/test/java/com/scopely/mapper/JsonNodeAttributeValueMapperTest.java
> +        node.put("key", ByteBuffer.wrap(base64BinaryInfo.getBytes("UTF-8")).array());
StandardCharsets.UTF8 or similar

2017-04-05 18:26 UTC, avram commented on src/test/java/com/scopely/mapper/TablePersistenceTest.java
> +        ByteBuffer bb = ByteBuffer.wrap("val".getBytes());
Here too

2017-04-06 08:22 UTC, merged